
logging:
  level:
    root: info
    com.kingtrustcloud.familytree: debug
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.kingtrustcloud.familytree.entity
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://192.168.91.30:3306/goffice?allowMultiQueries=true&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useAffectedRows=true&autoReconnect=true&rewriteBatchedStatements=true
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


 # redis:
  #  database: 0
  #  host: 106.10.90.23
  #  port: 30091
  #  password:
    # 连接超时时间（毫秒）
  #  timeout: 10000
  #  jedis:
  #    pool:
        # 连接池中的最大空闲连接
   #     max-idle: 8
        # 连接池中的最小空闲连接
  #      min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
   #     max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #    max-wait: -1
